version: "3"
services:
  strapi:
    env_file: .env
    build: ./
    image: cms-strapi:latest
    container_name: strapi-cms
    restart: unless-stopped
    environment:
      APP_NAME: strapi-cms
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
